Bulky My Project/BulkyBook/BulkyBookWeb/Areas/Admin/Controllers/CoverTypeController.cs
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Admin)]

    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<CoverType> objCoverTypesList = _unitOfWork.CoverType.GetAll();

            return View(objCoverTypesList);
        }

        // GET - Create
        public IActionResult Create()
        {
            return View();
        }

        // POST - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["success"] = "Cover Type created succesfully";
                return RedirectToAction("Index");
            }

            return View(obj);
        }


        // GET - Edit
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var coverTypeFromDb = _unitOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);

            if (coverTypeFromDb == null)
            {
                return NotFound();
            }

            return View(coverTypeFromDb);
        }

        // POST - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                TempData["success"] = "Cover Type created succesfully";
                return RedirectToAction("Index");
            }

            return View(obj);
        }

        // GET - Edit
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var coverTypeFromDb = _unitOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);

            if (coverTypeFromDb == null)
            {
                return NotFound();
            }

            return View(coverTypeFromDb);
        }

        // POST - Create
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var coverTypeFromDb = _unitOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);

            if (coverTypeFromDb == null)
            {
                return NotFound();
            }

            _unitOfWork.CoverType.Remove(coverTypeFromDb);
            _unitOfWork.Save();
            TempData["success"] = "Cover Type deleted succesfully";
            return RedirectToAction("Index");
        }
    }
}

Bulky My Project/BulkyBook/BulkyBookWeb/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
	<div class="border p-3 mt-4" style="width:50%">
		<div class="row pb-2">
			<h2 class="text-primary">Create Cover Type</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for = "Name"></label>
			<input asp-for = "Name" class="form-control"/>
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Create</button>
		<a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>

	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial"> </partial>
	}
}

Bulky My Project/BulkyBook/BulkyBookWeb/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

<form method="post" asp-action="Delete">
	@*<input asp-for="Id" hidden />*@
	<div class="border p-3 mt-4" style="width:50%">
		<div class="row pb-2">
			<h2 class="text-primary">Delete Cover Type</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for = "Name"></label>
			<input asp-for = "Name" class="form-control" readonly/>
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
		<a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>

	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial"> </partial>
	}
}

Bulky My Project/BulkyBook/BulkyBookWeb/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post" asp-action="Edit">
	<div class="border p-3 mt-4" style="width:50%">
		<div class="row pb-2">
			<h2 class="text-primary">Edit Cover Type</h2>
			<hr />
		</div>
		<div class="mb-3">
			<label asp-for = "Name"></label>
			<input asp-for = "Name" class="form-control"/>
			<span asp-validation-for="Name" class="text-danger"></span>
		</div>
		<button type="submit" class="btn btn-primary" style="width:150px">Update</button>
		<a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">
			Back to List
		</a>

	</div>
</form>

@section Scripts {
	@{
		<partial name="_ValidationScriptsPartial"> </partial>
	}
}

Bulky My Project/BulkyBook/BulkyBookWeb/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
	ViewData["Title"] = "Index";
}

<div class="container pt-4">
	<div class="row p-4">
		<div class="col-6">
			<h2 class="primary-text">List of Cover Types</h2>
		</div>
		<div class="col-6 text-end">
			<a asp-controller="CoverType" asp-action="Create" class="btn btn-primary">
				<i class="bi bi-plus-circle"></i> &nbsp; Create new Cover Type
			</a>
		</div>
	</div>
	<br /> <br />

	<table class="table table-bordered table-striped" style="width:100%">
		<thead>
			<tr>
				<th>
					Name of Cover Type
				</th>
				<th></th>
			</tr>
		</thead>
		<tbody>
			@foreach(var obj in Model)
			{
				<tr>
					<td width="50%">
						@obj.Name
					</td>
					<td>
						<div class="w-75 btn-group" role="group">
							<a asp-controller="CoverType" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
								<i class="bi bi-pencil-square"></i> Edit
							</a>
							<a asp-controller= "CoverType" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2">
								<i class="bi bi-trash3"></i> Delete
							</a>
						</div>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>